// Title: Realistic: code generation
// Summary: Generate a C# class and a SQL create table script from one table description. REMOVE_PREVIOUS drops the trailing comma of a column list.

using Toshal.Template.Examples.Support;

namespace Toshal.Template.Examples;

public static class CodeGenerationExample
{
    public record Column(string Name, string SqlType, bool Nullable, bool Key = false, string Comment = "")
    {
        public string PropertyName => string.Concat(Name.Split('_').Select(p => char.ToUpperInvariant(p[0]) + p[1..]));

        public string CsType => (SqlType, Nullable) switch
        {
            ("integer", false) => "int",
            ("integer", true) => "int?",
            ("text", false) => "string",
            ("text", true) => "string?",
            _ => "object",
        };

        public bool IsString => CsType == "string";

        public bool HasComment => Comment.Length > 0;
    }

    public record TableModel(string Table, string Namespace, List<Column> Columns)
    {
        public string ClassName => new Column(Table, "", false).PropertyName;

        public bool HasKey => Columns.Any(c => c.Key);
    }

    public static string Generate(string templateFile, TableModel table)
    {
        return ObjectProviders.Create().Process(new ProcessorArgs(EmbeddedTemplates.Tokens(templateFile)) { Context = table }).ToString();
    }

    public static void Run()
    {
        Console.WriteLine("== Code generation ==");

        var customer = new TableModel("customer", "Shop.Data",
        [
            new Column("id", "integer", Nullable: false, Key: true, Comment: "The customer number."),
            new Column("full_name", "text", Nullable: false),
            new Column("email", "text", Nullable: true),
        ]);

        string cs = Generate("Entity.rtt", customer);
        string sql = Generate("CreateTable.rtt", customer);
        Console.WriteLine(cs);
        Console.WriteLine(sql);

        Verify.Equal(
            "// <auto-generated>Made from the table customer. Do not edit by hand.</auto-generated>\n" +
            "namespace Shop.Data;\n" +
            "\n" +
            "public sealed class Customer\n" +
            "{\n" +
            "    /// <summary>The customer number.</summary>\n" +
            "    public int Id { get; set; }\n" +
            "    public string FullName { get; set; } = \"\";\n" +
            "    public string? Email { get; set; }\n" +
            "}",
            cs,
            "C# class");

        Verify.Equal(
            "create table customer\n" +
            "(\n" +
            "    id integer not null,\n" +
            "    full_name text not null,\n" +
            "    email text,\n" +
            "    primary key (id)\n" +
            ");",
            sql,
            "SQL script");
    }
}
