// Title: Realistic: generate a project structure
// Summary: A manifest template decides which files to create (the test project only when asked), and one template per file writes each of them into a folder. Shared parts come from a sub template.

using Toshal.Template.Examples.Support;
using Toshal.Template.Tokens;

namespace Toshal.Template.Examples;

public static class ProjectStructureExample
{
    public record Package(string Id, string Version);

    public record FileEntry(string Path);

    public record ProjectOptions(string Name, string Description, string Framework, bool WithTests, List<Package> Packages)
    {
        public List<FileEntry> Files { get; } = [];
    }

    /// <summary>Production code: writes the project into the folder and returns the relative paths it wrote.</summary>
    public static List<string> Generate(ProjectOptions options, string folder)
    {
        // Sub templates are looked up by name in the Project folder. Names arrive in lower case, file names are not, so compare without case.
        var processor = ObjectProviders.Create(subTemplates: args =>
        {
            string? file = EmbeddedTemplates.List("Project/").FirstOrDefault(f => f.Equals(args.Name + ".rtt", StringComparison.OrdinalIgnoreCase));
            return file == null ? null : EmbeddedTemplates.Tokens("Project/" + file);
        });

        string Render(string template) => processor.Process(new ProcessorArgs(EmbeddedTemplates.Tokens("Project/" + template)) { Context = options }).ToString();

        // 1. The manifest: one "path|template" line per file.
        var plan = Render("Manifest.rtt").Split('\n', StringSplitOptions.RemoveEmptyEntries).Select(l => l.Split('|')).ToList();
        options.Files.Clear();
        options.Files.AddRange(plan.Select(p => new FileEntry(p[0])));

        // 2. One template per file. The README lists the files, so it reads options.Files.
        foreach (var entry in plan)
        {
            string path = Path.Combine(folder, entry[0].Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, Render(entry[1]));
        }

        return plan.Select(p => p[0]).ToList();
    }

    public static void Run()
    {
        Console.WriteLine("== Project structure ==");

        string folder = Path.Combine(Path.GetTempPath(), "toshal-template-example-" + Guid.NewGuid().ToString("N"));
        try
        {
            var options = new ProjectOptions("Billing", "Creates the monthly invoices.", "net10.0", WithTests: true, [new Package("Serilog", "4.0.0")]);
            var written = Generate(options, folder);
            written.ForEach(f => Console.WriteLine("  " + f));

            Verify.That(written.Count == 5 && File.Exists(Path.Combine(folder, "tests", "Billing.Tests", "SmokeTests.cs")), "five files with tests");
            Verify.Equal(
                "// Generated by Toshal.Template for Billing. Change it as you like.\nConsole.WriteLine(\"Hello from Billing!\");",
                File.ReadAllText(Path.Combine(folder, "src", "Billing", "Program.cs")),
                "Program.cs with the shared header");
            Verify.That(File.ReadAllText(Path.Combine(folder, "src", "Billing", "Billing.csproj")).Contains("<PackageReference Include=\"Serilog\" Version=\"4.0.0\" />"), "package reference");
            Verify.That(File.ReadAllText(Path.Combine(folder, "README.md")).EndsWith("- `tests/Billing.Tests/SmokeTests.cs`"), "README lists the files");

            var small = Generate(new ProjectOptions("Tool", "A small tool.", "net10.0", WithTests: false, []), Path.Combine(folder, "small"));
            Verify.That(small.Count == 3 && !File.ReadAllText(Path.Combine(folder, "small", "src", "Tool", "Tool.csproj")).Contains("ItemGroup"), "no tests, no packages");
        }
        finally
        {
            if (Directory.Exists(folder)) Directory.Delete(folder, recursive: true);
        }
    }
}
