// <auto-generated>
//     Made by Toshal.Template from CompiledTemplates/Entity.ctt. Do not change this file; change the template.
// </auto-generated>

#nullable enable

namespace Toshal.Template.Examples.CompiledTemplates
{
    partial class Entity : global::Toshal.Template.Compiled.CompiledTemplate
    {
        private static readonly global::Toshal.Template.Tokens.TokenAttributeDictionary A0 = Attributes();

        private partial string? TokenValue(global::Toshal.Template.TokenArgs args);
        private partial bool Condition(global::Toshal.Template.ConditionArgs args);
        private partial global::System.Collections.IList? Loop(global::Toshal.Template.LoopArgs args);

        protected override void Render(global::System.Text.StringBuilder output, object? context, global::Toshal.Template.Compiled.TemplateRun run, ref global::Toshal.Template.Compiled.TemplateScope scope)
        {
            output.Append("// <auto-generated>Made from the table ");
            if (!scope.TryAppend(output, "table"))
            {
                var value0 = this.TokenValue(run.TokenArgs("table", A0, context));
                if (!string.IsNullOrEmpty(value0)) output.Append(value0);
            }
            output.Append(". Do not edit by hand.</auto-generated>\nnamespace ");
            if (!scope.TryAppend(output, "namespace"))
            {
                var value1 = this.TokenValue(run.TokenArgs("namespace", A0, context));
                if (!string.IsNullOrEmpty(value1)) output.Append(value1);
            }
            output.Append(";\n\npublic sealed class ");
            if (!scope.TryAppend(output, "classname"))
            {
                var value2 = this.TokenValue(run.TokenArgs("classname", A0, context));
                if (!string.IsNullOrEmpty(value2)) output.Append(value2);
            }
            output.Append("\n{");
            this.ForEach0(output, context, run.LoopArgs("columns", A0, context), run, ref scope);
            output.Append("\n}");
        }

        private void ForEach0(global::System.Text.StringBuilder output, object? context, global::Toshal.Template.LoopArgs args, global::Toshal.Template.Compiled.TemplateRun run, ref global::Toshal.Template.Compiled.TemplateScope scope)
        {
            var list = this.Loop(args);
            if (list == null || list.Count == 0)
            {
                return;
            }

            run.EnterLoop();
            var rowScope = global::Toshal.Template.Compiled.TemplateScope.Child(scope);
            run.ParentContext.Add(list);
            for (var i = 0; i < list.Count; i++)
            {
                var row = list[i];
                run.ParentContext.Add(row);
                run.SetRow(isLast: i == list.Count - 1);
                if (this.Condition(run.ConditionArgs("hascomment", A0, row)))
                {
                    output.Append("\n    /// <summary>");
                    if (!rowScope.TryAppend(output, "comment"))
                    {
                        var value3 = this.TokenValue(run.TokenArgs("comment", A0, row));
                        if (!string.IsNullOrEmpty(value3)) output.Append(value3);
                    }
                    output.Append("</summary>");
                }
                output.Append("\n    public ");
                if (!rowScope.TryAppend(output, "cstype"))
                {
                    var value4 = this.TokenValue(run.TokenArgs("cstype", A0, row));
                    if (!string.IsNullOrEmpty(value4)) output.Append(value4);
                }
                output.Append(" ");
                if (!rowScope.TryAppend(output, "propertyname"))
                {
                    var value5 = this.TokenValue(run.TokenArgs("propertyname", A0, row));
                    if (!string.IsNullOrEmpty(value5)) output.Append(value5);
                }
                output.Append(" { get; set; }");
                if (this.Condition(run.ConditionArgs("isstring", A0, row)))
                {
                    output.Append(" = \"\";");
                }
                run.RemoveParent(row);
            }

            run.LeaveRow();
            run.RemoveParent(list);
            run.ExitLoop();
        }
    }
}
